name: Build and deploy Symfony app to Azure Web App - webappjoan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer install --prefer-dist --no-progress --no-dev --optimize-autoloader

      - name: Build Symfony project
        run: |
          php bin/console cache:clear --env=prod
          php bin/console cache:warmup --env=prod

      - name: Zip artifact for deployment (complete project)
        run: zip -r release.zip ./* -x "node_modules/*" "tests/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: symfony-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: symfony-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d .

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'webappjoan'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
